import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import DashboardNavbar from "@/features/navbar/DashboardNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <DashboardNavbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
